- name: nuxeo-kafka-apb deprovision
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansibleplaybookbundle.asb-modules
  - role: nuxeo-kafka-apb
  vars:
    apb_action: deprovision
